import React from 'react';

const TermsAndConditions = () => {
  return (
    <div className="max-w-4xl mx-auto px-6 py-12 text-slate-800 leading-relaxed">
      <h1 className="text-3xl font-bold mb-6 border-b pb-4">Terms & Conditions</h1>
      
      <div className="space-y-6 text-sm md:text-base text-justify">
        <p className="italic text-slate-500">
          Last updated: March 06, 2026
        </p>

        <section>
          <p>
            This document is an electronic record in terms of Information Technology Act, 2000 
            and rules there under as applicable and the amended provisions pertaining to 
            electronic records in various statutes as amended by the Information Technology 
            Act, 2000. This electronic record is generated by a computer system and does not 
            require any physical or digital signatures.
          </p>
        </section>

        <section>
          <p>
            This document is published in accordance with the provisions of Rule 3 (1) of the 
            Information Technology (Intermediaries guidelines) Rules, 2011 that require 
            publishing the rules and regulations, privacy policy and Terms of Use for access 
            or usage of domain name <strong>https://thriftvault.vercel.app</strong> (&apos;Website&apos;).
          </p>
        </section>

        <section>
          <p>
            The Platform is owned by <strong>Ayush Tiwari (ThriftVault)</strong>, 
            operating from its registered office at <strong>IIT Ropar, Rupnagar, Punjab 140001</strong> 
            (hereinafter referred to as &lsquo;Platform Owner&rsquo;, &apos;we&apos;, &apos;us&apos;, &apos;our&apos;).
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold mb-3">Terms of Use</h2>
          <ul className="list-disc pl-5 space-y-3">
            <li>
              To access and use the Services, you agree to provide true, accurate and complete 
              information to us during and after registration.
            </li>
            <li>
              Your use of our Services and the Platform is solely and entirely at your own 
              risk and discretion.
            </li>
            <li>
              The contents of the Platform, including design, layout, look, and graphics, 
              are proprietary to us.
            </li>
            <li>
              You agree not to use the Platform for any purpose that is unlawful, illegal, 
              or forbidden by these Terms or Indian laws.
            </li>
            <li>
              You understand that initiating a transaction constitutes a legally binding 
              contract with the Platform Owner.
            </li>
            <li>
              All disputes arising out of or in connection with these Terms shall be subject 
              to the exclusive jurisdiction of the courts in <strong>Rupnagar, Punjab</strong>.
            </li>
          </ul>
        </section>

        <section className="bg-amber-50 p-4 rounded border border-amber-200 text-xs text-amber-900">
          <p className="font-bold">Important Notice:</p>
          <p>
            ACCESSING, BROWSING OR OTHERWISE USING THE PLATFORM INDICATES YOUR AGREEMENT 
            TO ALL THE TERMS AND CONDITIONS UNDER THESE TERMS OF USE. PLEASE READ THEM 
            CAREFULLY BEFORE PROCEEDING.
          </p>
        </section>

        <section>
          <p className="text-sm font-semibold">
            Contact us: All concerns regarding these Terms must be communicated to us 
            via the contact information provided on our Support page.
          </p>
        </section>
      </div>
    </div>
  );
};

export default TermsAndConditions;